# Generated by Django 5.2.5 on 2025-09-22 12:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('lugar', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('requiere_inscripcion', models.CharField(blank=True, max_length=1, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=1, null=True)),
                ('aforo', models.FloatField(blank=True, null=True)),
                ('fecha_apertura_ins', models.DateField(blank=True, null=True)),
                ('fecha_cierre_ins', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaPsicologos',
            fields=[
                ('id_agenda_slot', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_slot', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'agenda_psicologos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id_asistencia', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionesActividad',
            fields=[
                ('id_calificacion', models.FloatField(primary_key=True, serialize=False)),
                ('estrellas', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'calificaciones_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clasificaciones',
            fields=[
                ('pk', models.CompositePrimaryKey('torneos_id_torneo', 'equipos_id_equipo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pj', models.FloatField()),
                ('pg', models.FloatField()),
                ('pe', models.FloatField()),
                ('pp', models.FloatField()),
                ('gf', models.FloatField()),
                ('gc', models.FloatField()),
                ('pts', models.FloatField()),
            ],
            options={
                'db_table': 'clasificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'disciplinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('cantidad_personas', models.FloatField(blank=True, null=True)),
                ('capacidad_min', models.FloatField(blank=True, null=True)),
                ('capacidad_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosAsistencia',
            fields=[
                ('id_estado_asistencia', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados_asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosCita',
            fields=[
                ('id_estado_cita', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosParticipacion',
            fields=[
                ('id_estado_participacion', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados_participacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosTorneo',
            fields=[
                ('id_estado_torneo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'estados_torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FkProysocCoordinador',
            fields=[
                ('pk', models.CompositePrimaryKey('participantes_id_participante', 'proyectos_sociales_id_proyecto', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fk_proysoc_coordinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialCitas',
            fields=[
                ('id_historial', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nota', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'historial_citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialParticipaciones',
            fields=[
                ('id_historial', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nota', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'historial_participaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosParticipante',
            fields=[
                ('id_horario', models.FloatField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fuente_manual', models.CharField(blank=True, max_length=1, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'horarios_participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscripcionesPsu',
            fields=[
                ('id_inscripcion_psu', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
            ],
            options={
                'db_table': 'inscripciones_psu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotivosCita',
            fields=[
                ('id_motivo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'motivos_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.FloatField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id_participacion', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
            ],
            options={
                'db_table': 'participaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_participante', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('semestre', models.FloatField(blank=True, null=True)),
                ('estado_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('facultad', models.CharField(blank=True, max_length=80, null=True)),
                ('programa', models.CharField(blank=True, max_length=120, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'participantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('marcador_a', models.FloatField(blank=True, null=True)),
                ('marcador_b', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'partidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectosSociales',
            fields=[
                ('id_proyecto', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('coordinador_id', models.FloatField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('aforo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesParticipacion',
            fields=[
                ('id_rol_participacion', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles_participacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposActividad',
            fields=[
                ('id_tipo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposNotificacion',
            fields=[
                ('id_tipo_notificacion', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id_torneo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('reglas_elegibilidad', models.CharField(blank=True, max_length=1000, null=True)),
                ('aforo_equipos', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'torneos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TorneosEquipos',
            fields=[
                ('pk', models.CompositePrimaryKey('torneos_id_torneo', 'equipos_id_equipo', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'torneos_equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposParticipantes',
            fields=[
                ('equipos_id_equipo', models.OneToOneField(db_column='equipos_id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='universitaryWellbeing.equipos')),
                ('id_participante1', models.FloatField()),
            ],
            options={
                'db_table': 'equipos_participantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'category'], name='universitar_user_id_139b35_idx')],
            },
        ),
    ]
