# Generated by Django 5.2.5 on 2025-09-28 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('requiere_inscripcion', models.CharField(blank=True, max_length=1, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=1, null=True)),
                ('aforo', models.BigIntegerField(blank=True, null=True)),
                ('fecha_apertura_ins', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre_ins', models.DateTimeField(blank=True, null=True)),
                ('id_tipo', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesGrupos',
            fields=[
                ('id_actividad_grupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('actividades_id_actividad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'actividades_grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaPsicologos',
            fields=[
                ('id_agenda_slot', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado_slot', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'agenda_psicologos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id_asistencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionesActividad',
            fields=[
                ('id_calificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'calificaciones_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clasificaciones',
            fields=[
                ('pk', models.CompositePrimaryKey('torneos_id_torneo', 'equipos_id_equipo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pj', models.IntegerField()),
                ('pg', models.IntegerField()),
                ('pe', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('gf', models.IntegerField()),
                ('gc', models.IntegerField()),
                ('pts', models.IntegerField()),
            ],
            options={
                'db_table': 'clasificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'disciplinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField()),
                ('cantidad_personas', models.BigIntegerField(blank=True, null=True)),
                ('capacidad_min', models.IntegerField(blank=True, null=True)),
                ('capacidad_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosAsistencia',
            fields=[
                ('id_estado_asistencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados_asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosCita',
            fields=[
                ('id_estado_cita', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosParticipacion',
            fields=[
                ('id_estado_participacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados_participacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosTorneo',
            fields=[
                ('id_estado_torneo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'estados_torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FkProysocCoordinador',
            fields=[
                ('pk', models.CompositePrimaryKey('participantes_id_participante', 'proyectos_sociales_id_proyecto', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fk_proysoc_coordinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GruposActividad',
            fields=[
                ('id_grupo_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'grupos_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialCitas',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nota', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'historial_citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialParticipaciones',
            fields=[
                ('id_historial', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nota', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'historial_participaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosParticipante',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fuente_manual', models.CharField(max_length=1)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'horarios_participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InscripcionesPsu',
            fields=[
                ('id_inscripcion_psu', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField()),
            ],
            options={
                'db_table': 'inscripciones_psu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotivosCita',
            fields=[
                ('id_motivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'motivos_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participaciones',
            fields=[
                ('id_participacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField()),
            ],
            options={
                'db_table': 'participaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_participante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('semestre', models.BigIntegerField(blank=True, null=True)),
                ('estado_activo', models.CharField(blank=True, max_length=1, null=True)),
                ('facultad', models.CharField(blank=True, max_length=80, null=True)),
                ('programa', models.CharField(blank=True, max_length=120, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'participantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('marcador_a', models.IntegerField(blank=True, null=True)),
                ('marcador_b', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'partidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id_preferencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preferencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenciasActividades',
            fields=[
                ('id_preferencia_actividad', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'preferencias_actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectosSociales',
            fields=[
                ('id_proyecto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('coordinador_id', models.BigIntegerField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('aforo', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesParticipacion',
            fields=[
                ('id_rol_participacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles_participacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposActividad',
            fields=[
                ('id_tipo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposNotificacion',
            fields=[
                ('id_tipo_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id_torneo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('reglas_elegibilidad', models.CharField(blank=True, max_length=1000, null=True)),
                ('aforo_equipos', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'torneos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TorneosEquipos',
            fields=[
                ('pk', models.CompositePrimaryKey('torneos_id_torneo', 'equipos_id_equipo', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'torneos_equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposParticipantes',
            fields=[
                ('equipos_id_equipo', models.OneToOneField(db_column='equipos_id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='universitaryWellbeing.equipos')),
                ('id_participante1', models.BigIntegerField()),
            ],
            options={
                'db_table': 'equipos_participantes',
                'managed': False,
            },
        ),
    ]
