# Generated by Django 5.2.5 on 2025-09-26 13:20

import django.db.models.deletion
import universitaryWellbeing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesGrupos',
            fields=[
                ('id_actividad_grupo', models.FloatField(primary_key=True, serialize=False)),
                ('actividades_id_actividad', models.FloatField()),
            ],
            options={
                'db_table': 'actividades_grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GruposActividad',
            fields=[
                ('id_grupo_actividad', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=universitaryWellbeing.models.actividad_upload_to)),
            ],
            options={
                'db_table': 'grupos_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id_preferencia', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preferencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenciasActividades',
            fields=[
                ('id_preferencia_actividad', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'preferencias_actividades',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.CreateModel(
            name='HorarioActividad',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('espacio', models.CharField(max_length=150)),
                ('profesor', models.CharField(max_length=150)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='universitaryWellbeing.actividades')),
            ],
            options={
                'db_table': 'horarios_actividad',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
