# Generated by Django 5.2.5 on 2025-09-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0002_actividadesgrupos_grupos_gruposactividad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorarioActividad',
        ),
    ]
