# Generated by Django 5.2.5 on 2025-10-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
        ('universitaryWellbeing', '0003_delete_horarioactividad'),
    ]

    operations = [
    ]
