# Generated by Django 5.2.5 on 2025-10-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0004_merge_20251006_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
