# Generated by Django 5.2.5 on 2025-10-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0005_delete_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosActividad',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('profesor', models.CharField(blank=True, max_length=150, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'horarios_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosBloque',
            fields=[
                ('id_horario_bloque', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesor', models.CharField(blank=True, max_length=150, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'horarios_bloque',
                'managed': False,
            },
        ),
    ]
