# Generated by Django 5.2.5 on 2025-10-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0006_horariosactividad_horariosbloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPersonalizada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('profesor', models.CharField(blank=True, max_length=150, null=True)),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
            ],
            options={
                'db_table': 'materia_personalizada',
                'managed': False,
            },
        ),
    ]
