# Generated by Django 5.2.5 on 2025-10-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0007_materiapersonalizada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MateriaPersonalizada',
        ),
    ]
