# Generated by Django 5.2.7 on 2025-10-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0008_delete_materiapersonalizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'managed': True},
        ),
    ]
