# Generated by Django 5.2.7 on 2025-11-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0010_add_leida_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'managed': False},
        ),
    ]
