# Generated by Django 5.2.7 on 2025-11-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0010_add_leida_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_riesgo_critico', models.IntegerField(default=2, help_text='Asistencias mínimas + días sin asistir para riesgo crítico')),
                ('umbral_baja_asistencia', models.IntegerField(default=5, help_text='Asistencias mínimas para considerar baja asistencia')),
                ('dias_inactividad', models.IntegerField(default=14, help_text='Días sin asistir para considerar inactivo')),
                ('dias_riesgo_critico', models.IntegerField(default=21, help_text='Días de inactividad para riesgo crítico')),
                ('asistencias_reconocimiento', models.IntegerField(default=10, help_text='Asistencias necesarias para reconocimiento')),
                ('margen_proximo_reconocimiento', models.IntegerField(default=2, help_text='Asistencias faltantes para notificar proximidad')),
                ('asistencias_destacado', models.IntegerField(default=15, help_text='Asistencias para clasificar como destacado')),
                ('envio_automatico', models.BooleanField(default=True, help_text='Enviar notificaciones automáticamente')),
                ('frecuencia_envio', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal')], default='semanal', max_length=20)),
                ('emails_staff', models.TextField(default='luis.gluis.g.io.com@gmail.com', help_text='Emails separados por comas')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'configuracion_notificaciones',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'managed': False},
        ),
    ]
