# Generated by Django 5.2.7 on 2025-11-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0011_noticia_alter_notificaciones_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Noticias',
        ),
    ]
