# Generated by Django 5.2.7 on 2025-11-10 02:26

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0011_noticias_alter_notificaciones_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, quality=85, scale=None, size=[800, 600], upload_to='noticias/'),
        ),
    ]
