# Generated by Django 5.2.7 on 2025-11-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0011_configuracionnotificaciones_and_more'),
        ('universitaryWellbeing', '0012_alter_noticias_imagen'),
    ]

    operations = [
    ]
