# Generated by Django 5.2.7 on 2025-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0012_rename_noticia_noticias'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='noticias',
            table='noticias',
        ),
    ]
