# Generated by Django 5.2.7 on 2025-11-16 01:24

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0013_merge_20251115_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposParticipante',
            fields=[
                ('id_tipo_participante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('requiere_validacion', models.BooleanField(default=False, help_text='Requiere aprobación de admin (ej: Docentes)')),
                ('puede_crear_actividades', models.BooleanField(default=False, help_text='Puede crear actividades (ej: Coordinadores, Docentes)')),
                ('activo', models.BooleanField(default=True, help_text='Tipo disponible para selección')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en formularios')),
            ],
            options={
                'db_table': 'tipos_participante',
                'ordering': ['orden', 'nombre'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='configuracionnotificaciones',
            options={'managed': False, 'verbose_name': 'Configuración de Notificaciones', 'verbose_name_plural': 'Configuración de Notificaciones'},
        ),
        migrations.AlterField(
            model_name='noticias',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, quality=85, scale=None, size=[800, 450], upload_to='noticias/'),
        ),
    ]
