# Generated by Django 5.2.7 on 2025-11-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0013_alter_noticias_table'),
        ('universitaryWellbeing', '0014_tiposparticipante_and_more'),
    ]

    operations = [
    ]
