# Generated by Django 5.2.7 on 2025-11-16 21:24

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0015_merge_20251116_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='autor',
            field=models.CharField(db_column='autor', default='Administración Bienestar Universitario', max_length=100),
        ),
        migrations.AddField(
            model_name='noticias',
            name='enunciado',
            field=models.CharField(db_column='enunciado', default='No description available', max_length=300),
        ),
        migrations.AddField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.TextField(db_column='descripcion'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, quality=85, scale=None, size=[800, 450], upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(db_column='titulo', max_length=200),
        ),
    ]
