# Generated by Django 5.2.7 on 2025-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0016_noticias_autor_noticias_enunciado_noticias_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='autor',
            field=models.CharField(default='Administración Bienestar Universitario', max_length=100),
        ),
    ]
