# Generated by Django 5.2.7 on 2025-11-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0017_alter_noticias_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=200, unique=True),
        ),
    ]
