# Generated by Django 5.2.7 on 2025-11-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitaryWellbeing', '0018_alter_noticias_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
