name: bienestar-universitario

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bienestar-universitario
    container_name: bienestar-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  db:
    image: postgres:18
    container_name: database-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h9TZan8icTf3hjsn
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
volumes:
 postgres_data:
