[pytest]
DJANGO_SETTINGS_MODULE = BienestarUniversitario.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --nomigrations
markers =
    django_db: enable database access for tests
