-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.actividades DROP CONSTRAINT IF EXISTS actividades_actividades_grupos_fk;

ALTER TABLE IF EXISTS public.actividades DROP CONSTRAINT IF EXISTS actividades_tipos_actividad_fk;

ALTER TABLE IF EXISTS public.actividades DROP CONSTRAINT IF EXISTS fk_actividades_responsable;

ALTER TABLE IF EXISTS public.actividades_grupos DROP CONSTRAINT IF EXISTS actividades_grupos_grupos_actividad_fk;

ALTER TABLE IF EXISTS public.agenda_psicologos DROP CONSTRAINT IF EXISTS agenda_psicologos_participantes_fk;

ALTER TABLE IF EXISTS public.asistencias DROP CONSTRAINT IF EXISTS asistencias_estados_asistencia_fk;

ALTER TABLE IF EXISTS public.asistencias DROP CONSTRAINT IF EXISTS asistencias_participaciones_fk;

ALTER TABLE IF EXISTS public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;

ALTER TABLE IF EXISTS public.auth_group_permissions DROP CONSTRAINT IF EXISTS auth_group_permissions_group_id_b120cbf9_fk_auth_group_id;

ALTER TABLE IF EXISTS public.auth_permission DROP CONSTRAINT IF EXISTS auth_permission_content_type_id_2f476e4b_fk_django_co;

ALTER TABLE IF EXISTS public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_group_id_97559544_fk_auth_group_id;

ALTER TABLE IF EXISTS public.auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;

ALTER TABLE IF EXISTS public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm;

ALTER TABLE IF EXISTS public.auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id;

ALTER TABLE IF EXISTS public.calificaciones_actividad DROP CONSTRAINT IF EXISTS calificaciones_actividad_actividades_fk;

ALTER TABLE IF EXISTS public.calificaciones_actividad DROP CONSTRAINT IF EXISTS calificaciones_actividad_participantes_fk;

ALTER TABLE IF EXISTS public.citas DROP CONSTRAINT IF EXISTS citas_agenda_psicologos_fk;

ALTER TABLE IF EXISTS public.citas DROP CONSTRAINT IF EXISTS citas_estados_cita_fk;

ALTER TABLE IF EXISTS public.citas DROP CONSTRAINT IF EXISTS citas_motivos_cita_fk;

ALTER TABLE IF EXISTS public.citas DROP CONSTRAINT IF EXISTS citas_participantes_fk;

ALTER TABLE IF EXISTS public.citas DROP CONSTRAINT IF EXISTS citas_participantes_fkv2;

ALTER TABLE IF EXISTS public.clasificaciones DROP CONSTRAINT IF EXISTS clasificaciones_equipos_fk;

ALTER TABLE IF EXISTS public.clasificaciones DROP CONSTRAINT IF EXISTS clasificaciones_torneos_fk;

ALTER TABLE IF EXISTS public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_content_type_id_c4bce8eb_fk_django_co;

ALTER TABLE IF EXISTS public.django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;

ALTER TABLE IF EXISTS public.equipos DROP CONSTRAINT IF EXISTS equipos_disciplinas_fk;

ALTER TABLE IF EXISTS public.equipos DROP CONSTRAINT IF EXISTS equipos_participantes_fk;

ALTER TABLE IF EXISTS public.equipos_participantes DROP CONSTRAINT IF EXISTS equipos_participantes_equipos_fk;

ALTER TABLE IF EXISTS public.equipos_participantes DROP CONSTRAINT IF EXISTS equipos_participantes_participantes_fk;

ALTER TABLE IF EXISTS public.estados_cita DROP CONSTRAINT IF EXISTS estados_cita_citas_fk;

ALTER TABLE IF EXISTS public.fk_proysoc_coordinador DROP CONSTRAINT IF EXISTS fk_proysoc_coordinador_participantes_fk;

ALTER TABLE IF EXISTS public.fk_proysoc_coordinador DROP CONSTRAINT IF EXISTS fk_proysoc_coordinador_proyectos_sociales_fk;

ALTER TABLE IF EXISTS public.grupos_actividad DROP CONSTRAINT IF EXISTS grupos_actividad_grupos_fk;

ALTER TABLE IF EXISTS public.historial_citas DROP CONSTRAINT IF EXISTS historial_citas_citas_fk;

ALTER TABLE IF EXISTS public.historial_citas DROP CONSTRAINT IF EXISTS historial_citas_participantes_fk;

ALTER TABLE IF EXISTS public.historial_participaciones DROP CONSTRAINT IF EXISTS historial_participaciones_participaciones_fk;

ALTER TABLE IF EXISTS public.horarios_actividad DROP CONSTRAINT IF EXISTS horarios_actividad_actividades_id_actividad_fkey;

ALTER TABLE IF EXISTS public.horarios_actividad DROP CONSTRAINT IF EXISTS horarios_actividad_horario_bloque_id_fkey;

ALTER TABLE IF EXISTS public.horarios_bloque DROP CONSTRAINT IF EXISTS horarios_bloque_actividades_id_actividad_fkey;

ALTER TABLE IF EXISTS public.horarios_participante DROP CONSTRAINT IF EXISTS horarios_participante_actividades_fk;

ALTER TABLE IF EXISTS public.horarios_participante DROP CONSTRAINT IF EXISTS horarios_participante_citas_fk;

ALTER TABLE IF EXISTS public.horarios_participante DROP CONSTRAINT IF EXISTS horarios_participante_participantes_fk;

ALTER TABLE IF EXISTS public.horarios_participante DROP CONSTRAINT IF EXISTS horarios_participante_partidos_fk;

ALTER TABLE IF EXISTS public.inscripciones_psu DROP CONSTRAINT IF EXISTS inscripciones_psu_estados_participacion_fk;

ALTER TABLE IF EXISTS public.inscripciones_psu DROP CONSTRAINT IF EXISTS inscripciones_psu_participantes_fk;

ALTER TABLE IF EXISTS public.inscripciones_psu DROP CONSTRAINT IF EXISTS inscripciones_psu_proyectos_sociales_fk;

ALTER TABLE IF EXISTS public.motivos_cita DROP CONSTRAINT IF EXISTS motivos_cita_citas_fk;

ALTER TABLE IF EXISTS public.notificaciones DROP CONSTRAINT IF EXISTS fk_notif_actividad;

ALTER TABLE IF EXISTS public.notificaciones DROP CONSTRAINT IF EXISTS notificaciones_participantes_fk;

ALTER TABLE IF EXISTS public.notificaciones DROP CONSTRAINT IF EXISTS notificaciones_tipos_notificacion_fk;

ALTER TABLE IF EXISTS public.participaciones DROP CONSTRAINT IF EXISTS participaciones_actividades_fk;

ALTER TABLE IF EXISTS public.participaciones DROP CONSTRAINT IF EXISTS participaciones_equipos_fk;

ALTER TABLE IF EXISTS public.participaciones DROP CONSTRAINT IF EXISTS participaciones_estados_participacion_fk;

ALTER TABLE IF EXISTS public.participaciones DROP CONSTRAINT IF EXISTS participaciones_participantes_fk;

ALTER TABLE IF EXISTS public.participaciones DROP CONSTRAINT IF EXISTS participaciones_roles_participacion_fk;

ALTER TABLE IF EXISTS public.participantes DROP CONSTRAINT IF EXISTS fk_tipo_participante;

ALTER TABLE IF EXISTS public.participantes DROP CONSTRAINT IF EXISTS participantes_roles_fk;

ALTER TABLE IF EXISTS public.participantes DROP CONSTRAINT IF EXISTS participantes_user_fkey;

ALTER TABLE IF EXISTS public.partidos DROP CONSTRAINT IF EXISTS partidos_equipos_fk;

ALTER TABLE IF EXISTS public.partidos DROP CONSTRAINT IF EXISTS partidos_equipos_fkv2;

ALTER TABLE IF EXISTS public.partidos DROP CONSTRAINT IF EXISTS partidos_torneos_fk;

ALTER TABLE IF EXISTS public.preferencias DROP CONSTRAINT IF EXISTS preferencias_participantes_fk;

ALTER TABLE IF EXISTS public.preferencias_actividades DROP CONSTRAINT IF EXISTS preferencias_actividades_preferencias_fk;

ALTER TABLE IF EXISTS public.preferencias_actividades DROP CONSTRAINT IF EXISTS preferencias_actividades_tipos_id_actividad_fkey;

ALTER TABLE IF EXISTS public.roles DROP CONSTRAINT IF EXISTS fk_roles_group;

ALTER TABLE IF EXISTS public.torneos DROP CONSTRAINT IF EXISTS torneos_disciplinas_fk;

ALTER TABLE IF EXISTS public.torneos DROP CONSTRAINT IF EXISTS torneos_estados_torneo_fk;

ALTER TABLE IF EXISTS public.torneos_equipos DROP CONSTRAINT IF EXISTS torneos_equipos_equipos_fk;

ALTER TABLE IF EXISTS public.torneos_equipos DROP CONSTRAINT IF EXISTS torneos_equipos_torneos_fk;



DROP TABLE IF EXISTS public.actividades;

CREATE TABLE IF NOT EXISTS public.actividades
(
    id_actividad bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default",
    requiere_inscripcion character(1) COLLATE pg_catalog."default",
    modalidad character(1) COLLATE pg_catalog."default" DEFAULT 'I'::bpchar,
    aforo bigint,
    fecha_apertura_ins timestamp without time zone,
    fecha_cierre_ins timestamp without time zone,
    tipos_actividad_id_tipo bigint,
    act_grup_id bigint,
    promedio_calificacion double precision DEFAULT 0,
    responsable bigint,
    CONSTRAINT actividades_pkey PRIMARY KEY (id_actividad)
);

DROP TABLE IF EXISTS public.actividades_grupos;

CREATE TABLE IF NOT EXISTS public.actividades_grupos
(
    id_actividad_grupo bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    grp_act_id bigint NOT NULL,
    actividades_id_actividad bigint NOT NULL,
    CONSTRAINT actividades_grupos_pkey PRIMARY KEY (id_actividad_grupo),
    CONSTRAINT uq_actividades_grupos_pair UNIQUE (grp_act_id, actividades_id_actividad)
);

DROP TABLE IF EXISTS public.agenda_psicologos;

CREATE TABLE IF NOT EXISTS public.agenda_psicologos
(
    id_agenda_slot bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    participantes_id_participante bigint NOT NULL,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    estado_slot character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DISPONIBLE'::character varying,
    CONSTRAINT agenda_psicologos_pkey PRIMARY KEY (id_agenda_slot)
);

DROP TABLE IF EXISTS public.asistencias;

CREATE TABLE IF NOT EXISTS public.asistencias
(
    id_asistencia bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha timestamp without time zone NOT NULL,
    estados_asistencia_id_estado_asistencia bigint NOT NULL,
    participaciones_id_participacion bigint NOT NULL,
    CONSTRAINT asistencias_pkey PRIMARY KEY (id_asistencia)
);

ALTER TABLE IF EXISTS public.asistencias
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.auth_group;

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

DROP TABLE IF EXISTS public.auth_group_permissions;

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

DROP TABLE IF EXISTS public.auth_permission;

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

DROP TABLE IF EXISTS public.auth_user;

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

DROP TABLE IF EXISTS public.auth_user_groups;

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

DROP TABLE IF EXISTS public.auth_user_user_permissions;

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

DROP TABLE IF EXISTS public.calificaciones_actividad;

CREATE TABLE IF NOT EXISTS public.calificaciones_actividad
(
    id_calificacion bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    actividades_id_actividad bigint NOT NULL,
    participantes_id_participante bigint NOT NULL,
    estrellas integer NOT NULL,
    comentario character varying(500) COLLATE pg_catalog."default",
    fecha timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT calificaciones_actividad_pkey PRIMARY KEY (id_calificacion),
    CONSTRAINT uq_calificaciones_actividad_participante UNIQUE (actividades_id_actividad, participantes_id_participante)
);

DROP TABLE IF EXISTS public.citas;

CREATE TABLE IF NOT EXISTS public.citas
(
    id_cita bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha timestamp without time zone NOT NULL,
    motivo character varying(200) COLLATE pg_catalog."default",
    observaciones character varying(500) COLLATE pg_catalog."default",
    estados_cita_id_estado_cita bigint,
    participantes_id_participante bigint NOT NULL,
    participantes_id_participante2 bigint NOT NULL,
    motivos_cita_id_motivo bigint,
    agenda_psicologos_id_agenda_slot bigint,
    CONSTRAINT citas_pkey PRIMARY KEY (id_cita)
);

DROP TABLE IF EXISTS public.clasificaciones;

CREATE TABLE IF NOT EXISTS public.clasificaciones
(
    torneos_id_torneo bigint NOT NULL,
    equipos_id_equipo bigint NOT NULL,
    pj integer NOT NULL DEFAULT 0,
    pg integer NOT NULL DEFAULT 0,
    pe integer NOT NULL DEFAULT 0,
    pp integer NOT NULL DEFAULT 0,
    gf integer NOT NULL DEFAULT 0,
    gc integer NOT NULL DEFAULT 0,
    pts integer NOT NULL DEFAULT 0,
    CONSTRAINT clasificaciones_pk PRIMARY KEY (torneos_id_torneo, equipos_id_equipo)
);

DROP TABLE IF EXISTS public.configuracion_notificaciones;

CREATE TABLE IF NOT EXISTS public.configuracion_notificaciones
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    umbral_riesgo_critico integer NOT NULL,
    umbral_baja_asistencia integer NOT NULL,
    dias_inactividad integer NOT NULL,
    dias_riesgo_critico integer NOT NULL,
    asistencias_reconocimiento integer NOT NULL,
    margen_proximo_reconocimiento integer NOT NULL,
    asistencias_destacado integer NOT NULL,
    envio_automatico boolean NOT NULL,
    frecuencia_envio character varying(20) COLLATE pg_catalog."default" NOT NULL,
    emails_staff text COLLATE pg_catalog."default" NOT NULL,
    ultima_modificacion timestamp with time zone NOT NULL,
    hitos_reconocimiento character varying(100) COLLATE pg_catalog."default" DEFAULT '10,20,30,40,50'::character varying,
    reconocimientos_activos boolean DEFAULT true,
    dias_sin_asistir_alerta integer DEFAULT 7,
    dias_repetir_alerta_inasistencia integer DEFAULT 7,
    alertas_inasistencia_activas boolean DEFAULT true,
    asistencias_minimas_para_alertar integer DEFAULT 1,
    dias_despues_cierre_encuesta integer DEFAULT 7,
    asistencias_minimas_encuesta integer DEFAULT 3,
    encuestas_activas boolean DEFAULT true,
    recordatorio_cita_dias_antes integer DEFAULT 1,
    recordatorio_cita_horas_antes integer DEFAULT 2,
    recordatorios_citas_activos boolean DEFAULT true,
    recordatorio_evento_dias_antes integer DEFAULT 3,
    recordatorio_evento_dia_antes boolean DEFAULT true,
    recordatorios_eventos_activos boolean DEFAULT true,
    CONSTRAINT configuracion_notificaciones_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.disciplinas;

CREATE TABLE IF NOT EXISTS public.disciplinas
(
    id_disciplina bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT disciplinas_pkey PRIMARY KEY (id_disciplina),
    CONSTRAINT disciplinas_nombre_un UNIQUE (nombre)
);

DROP TABLE IF EXISTS public.django_admin_log;

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.django_content_type;

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

DROP TABLE IF EXISTS public.django_migrations;

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.django_session;

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

DROP TABLE IF EXISTS public.django_site;

CREATE TABLE IF NOT EXISTS public.django_site
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    domain character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_site_pkey PRIMARY KEY (id),
    CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain)
);

DROP TABLE IF EXISTS public.equipos;

CREATE TABLE IF NOT EXISTS public.equipos
(
    id_equipo bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp without time zone NOT NULL,
    cantidad_personas bigint,
    participantes_id_participante bigint NOT NULL,
    disciplinas_id_disciplina bigint,
    capacidad_min integer,
    capacidad_max integer,
    CONSTRAINT equipos_pkey PRIMARY KEY (id_equipo)
);

DROP TABLE IF EXISTS public.equipos_participantes;

CREATE TABLE IF NOT EXISTS public.equipos_participantes
(
    equipos_id_equipo bigint NOT NULL,
    participantes_id_participante bigint NOT NULL,
    id_participante1 bigint NOT NULL,
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT equipos_participantes_pkey PRIMARY KEY (id),
    CONSTRAINT uq_equipo_participante UNIQUE (equipos_id_equipo, participantes_id_participante)
);

DROP TABLE IF EXISTS public.estados_asistencia;

CREATE TABLE IF NOT EXISTS public.estados_asistencia
(
    id_estado_asistencia bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_asistencia_pkey PRIMARY KEY (id_estado_asistencia)
);

DROP TABLE IF EXISTS public.estados_cita;

CREATE TABLE IF NOT EXISTS public.estados_cita
(
    id_estado_cita bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    citas_id_cita bigint NOT NULL,
    CONSTRAINT estados_cita_pkey PRIMARY KEY (id_estado_cita)
);

DROP TABLE IF EXISTS public.estados_participacion;

CREATE TABLE IF NOT EXISTS public.estados_participacion
(
    id_estado_participacion bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_participacion_pkey PRIMARY KEY (id_estado_participacion)
);

DROP TABLE IF EXISTS public.estados_torneo;

CREATE TABLE IF NOT EXISTS public.estados_torneo
(
    id_estado_torneo bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_torneo_pkey PRIMARY KEY (id_estado_torneo),
    CONSTRAINT estados_torneo_nombre_un UNIQUE (nombre)
);

DROP TABLE IF EXISTS public.fk_proysoc_coordinador;

CREATE TABLE IF NOT EXISTS public.fk_proysoc_coordinador
(
    participantes_id_participante bigint NOT NULL,
    proyectos_sociales_id_proyecto bigint NOT NULL,
    CONSTRAINT fk_proysoc_coordinador_pk PRIMARY KEY (participantes_id_participante, proyectos_sociales_id_proyecto)
);

DROP TABLE IF EXISTS public.grupos;

CREATE TABLE IF NOT EXISTS public.grupos
(
    id_grupo bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT grupos_pkey PRIMARY KEY (id_grupo)
);

DROP TABLE IF EXISTS public.grupos_actividad;

CREATE TABLE IF NOT EXISTS public.grupos_actividad
(
    id_grupo_actividad bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    grupos_id_grupo bigint NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default",
    imagen character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT grupos_actividad_pkey PRIMARY KEY (id_grupo_actividad)
);

DROP TABLE IF EXISTS public.historial_citas;

CREATE TABLE IF NOT EXISTS public.historial_citas
(
    id_historial bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    citas_id_cita bigint NOT NULL,
    participantes_id_participante bigint NOT NULL,
    fecha timestamp without time zone NOT NULL DEFAULT now(),
    nota character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT historial_citas_pkey PRIMARY KEY (id_historial)
);

DROP TABLE IF EXISTS public.historial_participaciones;

CREATE TABLE IF NOT EXISTS public.historial_participaciones
(
    id_historial bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    participaciones_id_participacion bigint NOT NULL,
    fecha timestamp without time zone NOT NULL DEFAULT now(),
    nota character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT historial_participaciones_pkey PRIMARY KEY (id_historial)
);

DROP TABLE IF EXISTS public.horarios_actividad;

CREATE TABLE IF NOT EXISTS public.horarios_actividad
(
    id_horario bigserial NOT NULL,
    actividades_id_actividad bigint NOT NULL,
    dia_semana smallint NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    profesor character varying(150) COLLATE pg_catalog."default",
    lugar character varying(150) COLLATE pg_catalog."default",
    horario_bloque_id bigint,
    CONSTRAINT horarios_actividad_pkey PRIMARY KEY (id_horario),
    CONSTRAINT uq_hor_act_bloque_dia UNIQUE (horario_bloque_id, dia_semana),
    CONSTRAINT uq_horario_exact UNIQUE (actividades_id_actividad, dia_semana, hora_inicio, hora_fin)
);

ALTER TABLE IF EXISTS public.horarios_actividad
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.horarios_bloque;

CREATE TABLE IF NOT EXISTS public.horarios_bloque
(
    id_horario_bloque bigserial NOT NULL,
    actividades_id_actividad bigint NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    profesor character varying(150) COLLATE pg_catalog."default",
    lugar character varying(150) COLLATE pg_catalog."default",
    aforo integer,
    CONSTRAINT horarios_bloque_pkey PRIMARY KEY (id_horario_bloque),
    CONSTRAINT horarios_bloque_actividades_id_actividad_hora_inicio_hora_f_key UNIQUE (actividades_id_actividad, hora_inicio, hora_fin, profesor, lugar)
);

ALTER TABLE IF EXISTS public.horarios_bloque
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.horarios_participante;

CREATE TABLE IF NOT EXISTS public.horarios_participante
(
    id_horario bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    participantes_id_participante bigint NOT NULL,
    titulo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone NOT NULL,
    fuente_manual character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'S'::bpchar,
    actividades_id_actividad bigint,
    citas_id_cita bigint,
    partidos_id_partido bigint,
    notas character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT horarios_participante_pkey PRIMARY KEY (id_horario)
);

DROP TABLE IF EXISTS public.inscripciones_psu;

CREATE TABLE IF NOT EXISTS public.inscripciones_psu
(
    id_inscripcion_psu bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    participantes_id_participante bigint NOT NULL,
    proyectos_sociales_id_proyecto bigint NOT NULL,
    fecha_inscripcion timestamp without time zone NOT NULL DEFAULT now(),
    estados_participacion_id_estado_participacion bigint NOT NULL,
    CONSTRAINT inscripciones_psu_pkey PRIMARY KEY (id_inscripcion_psu),
    CONSTRAINT uq_inscripciones_psu_participante_proyecto UNIQUE (participantes_id_participante, proyectos_sociales_id_proyecto)
);

DROP TABLE IF EXISTS public.motivos_cita;

CREATE TABLE IF NOT EXISTS public.motivos_cita
(
    id_motivo bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(80) COLLATE pg_catalog."default" NOT NULL,
    citas_id_cita bigint,
    CONSTRAINT motivos_cita_pkey PRIMARY KEY (id_motivo),
    CONSTRAINT motivos_cita_nombre_un UNIQUE (nombre)
);

DROP TABLE IF EXISTS public.noticias;

CREATE TABLE IF NOT EXISTS public.noticias
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    titulo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    enunciado character varying(300) COLLATE pg_catalog."default" NOT NULL,
    autor character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    imagen character varying(100) COLLATE pg_catalog."default" NOT NULL,
    fecha_publicacion date NOT NULL,
    CONSTRAINT noticias_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.notificaciones;

CREATE TABLE IF NOT EXISTS public.notificaciones
(
    id_notificacion bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    mensaje character varying(500) COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp without time zone NOT NULL,
    participantes_id_participante bigint NOT NULL,
    tipos_notificacion_id_tipo_notificacion bigint NOT NULL,
    leida boolean NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    actividad_relacionada bigint,
    contexto_hito character varying(100) COLLATE pg_catalog."default",
    hash_unicidad character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT notificaciones_pkey PRIMARY KEY (id_notificacion)
);

DROP TABLE IF EXISTS public.participaciones;

CREATE TABLE IF NOT EXISTS public.participaciones
(
    id_participacion bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha_inscripcion timestamp without time zone NOT NULL,
    participantes_id_participante bigint NOT NULL,
    actividades_id_actividad bigint NOT NULL,
    roles_participacion_id_rol_participacion bigint NOT NULL,
    estados_participacion_id_estado_participacion bigint NOT NULL,
    equipos_id_equipo bigint,
    CONSTRAINT participaciones_pkey PRIMARY KEY (id_participacion),
    CONSTRAINT uq_participaciones_participante_actividad UNIQUE (participantes_id_participante, actividades_id_actividad)
);

ALTER TABLE IF EXISTS public.participaciones
    ENABLE ROW LEVEL SECURITY;

DROP TABLE IF EXISTS public.participantes;

CREATE TABLE IF NOT EXISTS public.participantes
(
    id_participante bigint NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(150) COLLATE pg_catalog."default" NOT NULL,
    semestre bigint,
    estado_activo character(1) COLLATE pg_catalog."default",
    roles_id_rol bigint NOT NULL,
    facultad character varying(80) COLLATE pg_catalog."default",
    programa character varying(120) COLLATE pg_catalog."default",
    genero character varying(20) COLLATE pg_catalog."default",
    "user" integer NOT NULL,
    tipo_participante_id bigint,
    CONSTRAINT participantes_pkey PRIMARY KEY (id_participante),
    CONSTRAINT participantes_correo_key UNIQUE (correo),
    CONSTRAINT participantes_user_key UNIQUE ("user")
);

DROP TABLE IF EXISTS public.partidos;

CREATE TABLE IF NOT EXISTS public.partidos
(
    id_partido bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    torneos_id_torneo bigint NOT NULL,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone,
    lugar character varying(150) COLLATE pg_catalog."default",
    equipos_id_equipo bigint NOT NULL,
    equipos_id_equipo2 bigint NOT NULL,
    marcador_a integer,
    marcador_b integer,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PROGRAMADO'::character varying,
    CONSTRAINT partidos_pkey PRIMARY KEY (id_partido)
);

DROP TABLE IF EXISTS public.preferencias;

CREATE TABLE IF NOT EXISTS public.preferencias
(
    id_preferencia bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    participantes_id_participante bigint NOT NULL,
    fecha_registro timestamp without time zone DEFAULT now(),
    CONSTRAINT preferencias_pkey PRIMARY KEY (id_preferencia),
    CONSTRAINT preferencias_participantes_id_participante_key UNIQUE (participantes_id_participante)
);

DROP TABLE IF EXISTS public.preferencias_actividades;

CREATE TABLE IF NOT EXISTS public.preferencias_actividades
(
    id_preferencia_actividad bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    preferencias_id_preferencia bigint NOT NULL,
    tipos_id_actividad bigint NOT NULL,
    CONSTRAINT preferencias_actividades_pkey PRIMARY KEY (id_preferencia_actividad),
    CONSTRAINT uq_preferencias_actividades UNIQUE (preferencias_id_preferencia, tipos_id_actividad)
);

DROP TABLE IF EXISTS public.proyectos_sociales;

CREATE TABLE IF NOT EXISTS public.proyectos_sociales
(
    id_proyecto bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(1000) COLLATE pg_catalog."default",
    coordinador_id bigint NOT NULL,
    fecha_inicio timestamp without time zone,
    fecha_fin timestamp without time zone,
    aforo bigint,
    CONSTRAINT proyectos_sociales_pkey PRIMARY KEY (id_proyecto)
);

DROP TABLE IF EXISTS public.roles;

CREATE TABLE IF NOT EXISTS public.roles
(
    id_rol bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre_rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    group_id integer,
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol),
    CONSTRAINT roles_group_id_key UNIQUE (group_id)
);

DROP TABLE IF EXISTS public.roles_participacion;

CREATE TABLE IF NOT EXISTS public.roles_participacion
(
    id_rol_participacion bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_participacion_pkey PRIMARY KEY (id_rol_participacion)
);

DROP TABLE IF EXISTS public.tipos_actividad;

CREATE TABLE IF NOT EXISTS public.tipos_actividad
(
    id_tipo bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre_tipo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tipos_actividad_pkey PRIMARY KEY (id_tipo)
);

DROP TABLE IF EXISTS public.tipos_notificacion;

CREATE TABLE IF NOT EXISTS public.tipos_notificacion
(
    id_tipo_notificacion bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipos_notificacion_pkey PRIMARY KEY (id_tipo_notificacion)
);

DROP TABLE IF EXISTS public.tipos_participante;

CREATE TABLE IF NOT EXISTS public.tipos_participante
(
    id_tipo_participante bigserial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    requiere_validacion boolean DEFAULT false,
    puede_crear_actividades boolean DEFAULT false,
    activo boolean DEFAULT true,
    orden integer DEFAULT 0,
    CONSTRAINT tipos_participante_pkey PRIMARY KEY (id_tipo_participante),
    CONSTRAINT tipos_participante_nombre_key UNIQUE (nombre)
);

DROP TABLE IF EXISTS public.torneos;

CREATE TABLE IF NOT EXISTS public.torneos
(
    id_torneo bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    disciplinas_id_disciplina bigint NOT NULL,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone NOT NULL,
    estados_torneo_id_estado_torneo bigint NOT NULL,
    reglas_elegibilidad character varying(1000) COLLATE pg_catalog."default",
    aforo_equipos bigint,
    limite_inscripcion timestamp without time zone,
    CONSTRAINT torneos_pkey PRIMARY KEY (id_torneo)
);

DROP TABLE IF EXISTS public.torneos_equipos;

CREATE TABLE IF NOT EXISTS public.torneos_equipos
(
    torneos_id_torneo bigint NOT NULL,
    equipos_id_equipo bigint NOT NULL,
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT torneos_equipos_pkey PRIMARY KEY (id),
    CONSTRAINT uq_torneo_equipo UNIQUE (torneos_id_torneo, equipos_id_equipo)
);

ALTER TABLE IF EXISTS public.actividades
    ADD CONSTRAINT actividades_actividades_grupos_fk FOREIGN KEY (act_grup_id)
    REFERENCES public.actividades_grupos (id_actividad_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.actividades
    ADD CONSTRAINT actividades_tipos_actividad_fk FOREIGN KEY (tipos_actividad_id_tipo)
    REFERENCES public.tipos_actividad (id_tipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.actividades
    ADD CONSTRAINT fk_actividades_responsable FOREIGN KEY (responsable)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_actividades_responsable
    ON public.actividades(responsable);


ALTER TABLE IF EXISTS public.actividades_grupos
    ADD CONSTRAINT actividades_grupos_grupos_actividad_fk FOREIGN KEY (grp_act_id)
    REFERENCES public.grupos_actividad (id_grupo_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.agenda_psicologos
    ADD CONSTRAINT agenda_psicologos_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.asistencias
    ADD CONSTRAINT asistencias_estados_asistencia_fk FOREIGN KEY (estados_asistencia_id_estado_asistencia)
    REFERENCES public.estados_asistencia (id_estado_asistencia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.asistencias
    ADD CONSTRAINT asistencias_participaciones_fk FOREIGN KEY (participaciones_id_participacion)
    REFERENCES public.participaciones (id_participacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.calificaciones_actividad
    ADD CONSTRAINT calificaciones_actividad_actividades_fk FOREIGN KEY (actividades_id_actividad)
    REFERENCES public.actividades (id_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.calificaciones_actividad
    ADD CONSTRAINT calificaciones_actividad_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_agenda_psicologos_fk FOREIGN KEY (agenda_psicologos_id_agenda_slot)
    REFERENCES public.agenda_psicologos (id_agenda_slot) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_estados_cita_fk FOREIGN KEY (estados_cita_id_estado_cita)
    REFERENCES public.estados_cita (id_estado_cita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS citas__idx
    ON public.citas(estados_cita_id_estado_cita);


ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_motivos_cita_fk FOREIGN KEY (motivos_cita_id_motivo)
    REFERENCES public.motivos_cita (id_motivo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS citas__idxv1
    ON public.citas(motivos_cita_id_motivo);


ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.citas
    ADD CONSTRAINT citas_participantes_fkv2 FOREIGN KEY (participantes_id_participante2)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clasificaciones
    ADD CONSTRAINT clasificaciones_equipos_fk FOREIGN KEY (equipos_id_equipo)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clasificaciones
    ADD CONSTRAINT clasificaciones_torneos_fk FOREIGN KEY (torneos_id_torneo)
    REFERENCES public.torneos (id_torneo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.equipos
    ADD CONSTRAINT equipos_disciplinas_fk FOREIGN KEY (disciplinas_id_disciplina)
    REFERENCES public.disciplinas (id_disciplina) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipos
    ADD CONSTRAINT equipos_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipos_participantes
    ADD CONSTRAINT equipos_participantes_equipos_fk FOREIGN KEY (equipos_id_equipo)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipos_participantes
    ADD CONSTRAINT equipos_participantes_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.estados_cita
    ADD CONSTRAINT estados_cita_citas_fk FOREIGN KEY (citas_id_cita)
    REFERENCES public.citas (id_cita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS estados_cita__idx
    ON public.estados_cita(citas_id_cita);


ALTER TABLE IF EXISTS public.fk_proysoc_coordinador
    ADD CONSTRAINT fk_proysoc_coordinador_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fk_proysoc_coordinador
    ADD CONSTRAINT fk_proysoc_coordinador_proyectos_sociales_fk FOREIGN KEY (proyectos_sociales_id_proyecto)
    REFERENCES public.proyectos_sociales (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grupos_actividad
    ADD CONSTRAINT grupos_actividad_grupos_fk FOREIGN KEY (grupos_id_grupo)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_citas
    ADD CONSTRAINT historial_citas_citas_fk FOREIGN KEY (citas_id_cita)
    REFERENCES public.citas (id_cita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_citas
    ADD CONSTRAINT historial_citas_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historial_participaciones
    ADD CONSTRAINT historial_participaciones_participaciones_fk FOREIGN KEY (participaciones_id_participacion)
    REFERENCES public.participaciones (id_participacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horarios_actividad
    ADD CONSTRAINT horarios_actividad_actividades_id_actividad_fkey FOREIGN KEY (actividades_id_actividad)
    REFERENCES public.actividades (id_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.horarios_actividad
    ADD CONSTRAINT horarios_actividad_horario_bloque_id_fkey FOREIGN KEY (horario_bloque_id)
    REFERENCES public.horarios_bloque (id_horario_bloque) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_hor_act_bloque
    ON public.horarios_actividad(horario_bloque_id);


ALTER TABLE IF EXISTS public.horarios_bloque
    ADD CONSTRAINT horarios_bloque_actividades_id_actividad_fkey FOREIGN KEY (actividades_id_actividad)
    REFERENCES public.actividades (id_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.horarios_participante
    ADD CONSTRAINT horarios_participante_actividades_fk FOREIGN KEY (actividades_id_actividad)
    REFERENCES public.actividades (id_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horarios_participante
    ADD CONSTRAINT horarios_participante_citas_fk FOREIGN KEY (citas_id_cita)
    REFERENCES public.citas (id_cita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horarios_participante
    ADD CONSTRAINT horarios_participante_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.horarios_participante
    ADD CONSTRAINT horarios_participante_partidos_fk FOREIGN KEY (partidos_id_partido)
    REFERENCES public.partidos (id_partido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripciones_psu
    ADD CONSTRAINT inscripciones_psu_estados_participacion_fk FOREIGN KEY (estados_participacion_id_estado_participacion)
    REFERENCES public.estados_participacion (id_estado_participacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripciones_psu
    ADD CONSTRAINT inscripciones_psu_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripciones_psu
    ADD CONSTRAINT inscripciones_psu_proyectos_sociales_fk FOREIGN KEY (proyectos_sociales_id_proyecto)
    REFERENCES public.proyectos_sociales (id_proyecto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.motivos_cita
    ADD CONSTRAINT motivos_cita_citas_fk FOREIGN KEY (citas_id_cita)
    REFERENCES public.citas (id_cita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS motivos_cita__idx
    ON public.motivos_cita(citas_id_cita);


ALTER TABLE IF EXISTS public.notificaciones
    ADD CONSTRAINT fk_notif_actividad FOREIGN KEY (actividad_relacionada)
    REFERENCES public.actividades (id_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.notificaciones
    ADD CONSTRAINT notificaciones_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notificaciones
    ADD CONSTRAINT notificaciones_tipos_notificacion_fk FOREIGN KEY (tipos_notificacion_id_tipo_notificacion)
    REFERENCES public.tipos_notificacion (id_tipo_notificacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participaciones
    ADD CONSTRAINT participaciones_actividades_fk FOREIGN KEY (actividades_id_actividad)
    REFERENCES public.actividades (id_actividad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participaciones
    ADD CONSTRAINT participaciones_equipos_fk FOREIGN KEY (equipos_id_equipo)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participaciones
    ADD CONSTRAINT participaciones_estados_participacion_fk FOREIGN KEY (estados_participacion_id_estado_participacion)
    REFERENCES public.estados_participacion (id_estado_participacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participaciones
    ADD CONSTRAINT participaciones_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participaciones
    ADD CONSTRAINT participaciones_roles_participacion_fk FOREIGN KEY (roles_participacion_id_rol_participacion)
    REFERENCES public.roles_participacion (id_rol_participacion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participantes
    ADD CONSTRAINT fk_tipo_participante FOREIGN KEY (tipo_participante_id)
    REFERENCES public.tipos_participante (id_tipo_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participantes
    ADD CONSTRAINT participantes_roles_fk FOREIGN KEY (roles_id_rol)
    REFERENCES public.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.participantes
    ADD CONSTRAINT participantes_user_fkey FOREIGN KEY ("user")
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET DEFAULT;
CREATE INDEX IF NOT EXISTS participantes_user_key
    ON public.participantes("user");


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT partidos_equipos_fk FOREIGN KEY (equipos_id_equipo)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT partidos_equipos_fkv2 FOREIGN KEY (equipos_id_equipo2)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.partidos
    ADD CONSTRAINT partidos_torneos_fk FOREIGN KEY (torneos_id_torneo)
    REFERENCES public.torneos (id_torneo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.preferencias
    ADD CONSTRAINT preferencias_participantes_fk FOREIGN KEY (participantes_id_participante)
    REFERENCES public.participantes (id_participante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS preferencias_participantes_id_participante_key
    ON public.preferencias(participantes_id_participante);


ALTER TABLE IF EXISTS public.preferencias_actividades
    ADD CONSTRAINT preferencias_actividades_preferencias_fk FOREIGN KEY (preferencias_id_preferencia)
    REFERENCES public.preferencias (id_preferencia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.preferencias_actividades
    ADD CONSTRAINT preferencias_actividades_tipos_id_actividad_fkey FOREIGN KEY (tipos_id_actividad)
    REFERENCES public.tipos_actividad (id_tipo) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.roles
    ADD CONSTRAINT fk_roles_group FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS roles_group_id_key
    ON public.roles(group_id);


ALTER TABLE IF EXISTS public.torneos
    ADD CONSTRAINT torneos_disciplinas_fk FOREIGN KEY (disciplinas_id_disciplina)
    REFERENCES public.disciplinas (id_disciplina) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.torneos
    ADD CONSTRAINT torneos_estados_torneo_fk FOREIGN KEY (estados_torneo_id_estado_torneo)
    REFERENCES public.estados_torneo (id_estado_torneo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.torneos_equipos
    ADD CONSTRAINT torneos_equipos_equipos_fk FOREIGN KEY (equipos_id_equipo)
    REFERENCES public.equipos (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.torneos_equipos
    ADD CONSTRAINT torneos_equipos_torneos_fk FOREIGN KEY (torneos_id_torneo)
    REFERENCES public.torneos (id_torneo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;